// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/google/csharp_options.proto

package google.protobuf;

public final class CsharpOptions {
  private CsharpOptions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(google.protobuf.CsharpOptions.csharpFileOptions);
    registry.add(google.protobuf.CsharpOptions.csharpFieldOptions);
    registry.add(google.protobuf.CsharpOptions.csharpServiceOptions);
    registry.add(google.protobuf.CsharpOptions.csharpMethodOptions);
  }
  public enum CSharpServiceType
      implements com.google.protobuf.ProtocolMessageEnum {
    NONE(0, 0),
    GENERIC(1, 1),
    INTERFACE(2, 2),
    IRPCDISPATCH(3, 3),
    ;
    
    public static final int NONE_VALUE = 0;
    public static final int GENERIC_VALUE = 1;
    public static final int INTERFACE_VALUE = 2;
    public static final int IRPCDISPATCH_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static CSharpServiceType valueOf(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return GENERIC;
        case 2: return INTERFACE;
        case 3: return IRPCDISPATCH;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CSharpServiceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CSharpServiceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CSharpServiceType>() {
            public CSharpServiceType findValueByNumber(int number) {
              return CSharpServiceType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return google.protobuf.CsharpOptions.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final CSharpServiceType[] VALUES = {
      NONE, GENERIC, INTERFACE, IRPCDISPATCH, 
    };
    
    public static CSharpServiceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CSharpServiceType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:google.protobuf.CSharpServiceType)
  }
  
  public interface CSharpFileOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string namespace = 1;
    boolean hasNamespace();
    String getNamespace();
    
    // optional string umbrella_classname = 2;
    boolean hasUmbrellaClassname();
    String getUmbrellaClassname();
    
    // optional bool public_classes = 3 [default = true];
    boolean hasPublicClasses();
    boolean getPublicClasses();
    
    // optional bool multiple_files = 4;
    boolean hasMultipleFiles();
    boolean getMultipleFiles();
    
    // optional bool nest_classes = 5;
    boolean hasNestClasses();
    boolean getNestClasses();
    
    // optional bool code_contracts = 6;
    boolean hasCodeContracts();
    boolean getCodeContracts();
    
    // optional bool expand_namespace_directories = 7;
    boolean hasExpandNamespaceDirectories();
    boolean getExpandNamespaceDirectories();
    
    // optional bool cls_compliance = 8 [default = true];
    boolean hasClsCompliance();
    boolean getClsCompliance();
    
    // optional bool add_serializable = 9 [default = false];
    boolean hasAddSerializable();
    boolean getAddSerializable();
    
    // optional bool generate_private_ctor = 10 [default = true];
    boolean hasGeneratePrivateCtor();
    boolean getGeneratePrivateCtor();
    
    // optional string file_extension = 221 [default = ".cs"];
    boolean hasFileExtension();
    String getFileExtension();
    
    // optional string umbrella_namespace = 222;
    boolean hasUmbrellaNamespace();
    String getUmbrellaNamespace();
    
    // optional string output_directory = 223 [default = "."];
    boolean hasOutputDirectory();
    String getOutputDirectory();
    
    // optional bool ignore_google_protobuf = 224 [default = false];
    boolean hasIgnoreGoogleProtobuf();
    boolean getIgnoreGoogleProtobuf();
    
    // optional .google.protobuf.CSharpServiceType service_generator_type = 225 [default = NONE];
    boolean hasServiceGeneratorType();
    google.protobuf.CsharpOptions.CSharpServiceType getServiceGeneratorType();
  }
  public static final class CSharpFileOptions extends
      com.google.protobuf.GeneratedMessage
      implements CSharpFileOptionsOrBuilder {
    // Use CSharpFileOptions.newBuilder() to construct.
    private CSharpFileOptions(Builder builder) {
      super(builder);
    }
    private CSharpFileOptions(boolean noInit) {}
    
    private static final CSharpFileOptions defaultInstance;
    public static CSharpFileOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSharpFileOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpFileOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpFileOptions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string namespace = 1;
    public static final int NAMESPACE_FIELD_NUMBER = 1;
    private java.lang.Object namespace_;
    public boolean hasNamespace() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNamespace() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          namespace_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string umbrella_classname = 2;
    public static final int UMBRELLA_CLASSNAME_FIELD_NUMBER = 2;
    private java.lang.Object umbrellaClassname_;
    public boolean hasUmbrellaClassname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getUmbrellaClassname() {
      java.lang.Object ref = umbrellaClassname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          umbrellaClassname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUmbrellaClassnameBytes() {
      java.lang.Object ref = umbrellaClassname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        umbrellaClassname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool public_classes = 3 [default = true];
    public static final int PUBLIC_CLASSES_FIELD_NUMBER = 3;
    private boolean publicClasses_;
    public boolean hasPublicClasses() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getPublicClasses() {
      return publicClasses_;
    }
    
    // optional bool multiple_files = 4;
    public static final int MULTIPLE_FILES_FIELD_NUMBER = 4;
    private boolean multipleFiles_;
    public boolean hasMultipleFiles() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public boolean getMultipleFiles() {
      return multipleFiles_;
    }
    
    // optional bool nest_classes = 5;
    public static final int NEST_CLASSES_FIELD_NUMBER = 5;
    private boolean nestClasses_;
    public boolean hasNestClasses() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getNestClasses() {
      return nestClasses_;
    }
    
    // optional bool code_contracts = 6;
    public static final int CODE_CONTRACTS_FIELD_NUMBER = 6;
    private boolean codeContracts_;
    public boolean hasCodeContracts() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public boolean getCodeContracts() {
      return codeContracts_;
    }
    
    // optional bool expand_namespace_directories = 7;
    public static final int EXPAND_NAMESPACE_DIRECTORIES_FIELD_NUMBER = 7;
    private boolean expandNamespaceDirectories_;
    public boolean hasExpandNamespaceDirectories() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getExpandNamespaceDirectories() {
      return expandNamespaceDirectories_;
    }
    
    // optional bool cls_compliance = 8 [default = true];
    public static final int CLS_COMPLIANCE_FIELD_NUMBER = 8;
    private boolean clsCompliance_;
    public boolean hasClsCompliance() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public boolean getClsCompliance() {
      return clsCompliance_;
    }
    
    // optional bool add_serializable = 9 [default = false];
    public static final int ADD_SERIALIZABLE_FIELD_NUMBER = 9;
    private boolean addSerializable_;
    public boolean hasAddSerializable() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public boolean getAddSerializable() {
      return addSerializable_;
    }
    
    // optional bool generate_private_ctor = 10 [default = true];
    public static final int GENERATE_PRIVATE_CTOR_FIELD_NUMBER = 10;
    private boolean generatePrivateCtor_;
    public boolean hasGeneratePrivateCtor() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public boolean getGeneratePrivateCtor() {
      return generatePrivateCtor_;
    }
    
    // optional string file_extension = 221 [default = ".cs"];
    public static final int FILE_EXTENSION_FIELD_NUMBER = 221;
    private java.lang.Object fileExtension_;
    public boolean hasFileExtension() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getFileExtension() {
      java.lang.Object ref = fileExtension_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fileExtension_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFileExtensionBytes() {
      java.lang.Object ref = fileExtension_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fileExtension_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string umbrella_namespace = 222;
    public static final int UMBRELLA_NAMESPACE_FIELD_NUMBER = 222;
    private java.lang.Object umbrellaNamespace_;
    public boolean hasUmbrellaNamespace() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getUmbrellaNamespace() {
      java.lang.Object ref = umbrellaNamespace_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          umbrellaNamespace_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUmbrellaNamespaceBytes() {
      java.lang.Object ref = umbrellaNamespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        umbrellaNamespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string output_directory = 223 [default = "."];
    public static final int OUTPUT_DIRECTORY_FIELD_NUMBER = 223;
    private java.lang.Object outputDirectory_;
    public boolean hasOutputDirectory() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getOutputDirectory() {
      java.lang.Object ref = outputDirectory_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          outputDirectory_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOutputDirectoryBytes() {
      java.lang.Object ref = outputDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        outputDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool ignore_google_protobuf = 224 [default = false];
    public static final int IGNORE_GOOGLE_PROTOBUF_FIELD_NUMBER = 224;
    private boolean ignoreGoogleProtobuf_;
    public boolean hasIgnoreGoogleProtobuf() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public boolean getIgnoreGoogleProtobuf() {
      return ignoreGoogleProtobuf_;
    }
    
    // optional .google.protobuf.CSharpServiceType service_generator_type = 225 [default = NONE];
    public static final int SERVICE_GENERATOR_TYPE_FIELD_NUMBER = 225;
    private google.protobuf.CsharpOptions.CSharpServiceType serviceGeneratorType_;
    public boolean hasServiceGeneratorType() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    public google.protobuf.CsharpOptions.CSharpServiceType getServiceGeneratorType() {
      return serviceGeneratorType_;
    }
    
    private void initFields() {
      namespace_ = "";
      umbrellaClassname_ = "";
      publicClasses_ = true;
      multipleFiles_ = false;
      nestClasses_ = false;
      codeContracts_ = false;
      expandNamespaceDirectories_ = false;
      clsCompliance_ = true;
      addSerializable_ = false;
      generatePrivateCtor_ = true;
      fileExtension_ = ".cs";
      umbrellaNamespace_ = "";
      outputDirectory_ = ".";
      ignoreGoogleProtobuf_ = false;
      serviceGeneratorType_ = google.protobuf.CsharpOptions.CSharpServiceType.NONE;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNamespaceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUmbrellaClassnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, publicClasses_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, multipleFiles_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, nestClasses_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, codeContracts_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, expandNamespaceDirectories_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(8, clsCompliance_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(9, addSerializable_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBool(10, generatePrivateCtor_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(221, getFileExtensionBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(222, getUmbrellaNamespaceBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(223, getOutputDirectoryBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeBool(224, ignoreGoogleProtobuf_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeEnum(225, serviceGeneratorType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNamespaceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUmbrellaClassnameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, publicClasses_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, multipleFiles_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, nestClasses_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, codeContracts_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, expandNamespaceDirectories_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, clsCompliance_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, addSerializable_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, generatePrivateCtor_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(221, getFileExtensionBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(222, getUmbrellaNamespaceBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(223, getOutputDirectoryBytes());
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(224, ignoreGoogleProtobuf_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(225, serviceGeneratorType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFileOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(google.protobuf.CsharpOptions.CSharpFileOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements google.protobuf.CsharpOptions.CSharpFileOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpFileOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpFileOptions_fieldAccessorTable;
      }
      
      // Construct using google.protobuf.CsharpOptions.CSharpFileOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        namespace_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        umbrellaClassname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        publicClasses_ = true;
        bitField0_ = (bitField0_ & ~0x00000004);
        multipleFiles_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        nestClasses_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        codeContracts_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        expandNamespaceDirectories_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        clsCompliance_ = true;
        bitField0_ = (bitField0_ & ~0x00000080);
        addSerializable_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        generatePrivateCtor_ = true;
        bitField0_ = (bitField0_ & ~0x00000200);
        fileExtension_ = ".cs";
        bitField0_ = (bitField0_ & ~0x00000400);
        umbrellaNamespace_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        outputDirectory_ = ".";
        bitField0_ = (bitField0_ & ~0x00001000);
        ignoreGoogleProtobuf_ = false;
        bitField0_ = (bitField0_ & ~0x00002000);
        serviceGeneratorType_ = google.protobuf.CsharpOptions.CSharpServiceType.NONE;
        bitField0_ = (bitField0_ & ~0x00004000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.CsharpOptions.CSharpFileOptions.getDescriptor();
      }
      
      public google.protobuf.CsharpOptions.CSharpFileOptions getDefaultInstanceForType() {
        return google.protobuf.CsharpOptions.CSharpFileOptions.getDefaultInstance();
      }
      
      public google.protobuf.CsharpOptions.CSharpFileOptions build() {
        google.protobuf.CsharpOptions.CSharpFileOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private google.protobuf.CsharpOptions.CSharpFileOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        google.protobuf.CsharpOptions.CSharpFileOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public google.protobuf.CsharpOptions.CSharpFileOptions buildPartial() {
        google.protobuf.CsharpOptions.CSharpFileOptions result = new google.protobuf.CsharpOptions.CSharpFileOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.namespace_ = namespace_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.umbrellaClassname_ = umbrellaClassname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.publicClasses_ = publicClasses_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.multipleFiles_ = multipleFiles_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.nestClasses_ = nestClasses_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.codeContracts_ = codeContracts_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.expandNamespaceDirectories_ = expandNamespaceDirectories_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.clsCompliance_ = clsCompliance_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.addSerializable_ = addSerializable_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.generatePrivateCtor_ = generatePrivateCtor_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.fileExtension_ = fileExtension_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.umbrellaNamespace_ = umbrellaNamespace_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.outputDirectory_ = outputDirectory_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.ignoreGoogleProtobuf_ = ignoreGoogleProtobuf_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.serviceGeneratorType_ = serviceGeneratorType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.CsharpOptions.CSharpFileOptions) {
          return mergeFrom((google.protobuf.CsharpOptions.CSharpFileOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(google.protobuf.CsharpOptions.CSharpFileOptions other) {
        if (other == google.protobuf.CsharpOptions.CSharpFileOptions.getDefaultInstance()) return this;
        if (other.hasNamespace()) {
          setNamespace(other.getNamespace());
        }
        if (other.hasUmbrellaClassname()) {
          setUmbrellaClassname(other.getUmbrellaClassname());
        }
        if (other.hasPublicClasses()) {
          setPublicClasses(other.getPublicClasses());
        }
        if (other.hasMultipleFiles()) {
          setMultipleFiles(other.getMultipleFiles());
        }
        if (other.hasNestClasses()) {
          setNestClasses(other.getNestClasses());
        }
        if (other.hasCodeContracts()) {
          setCodeContracts(other.getCodeContracts());
        }
        if (other.hasExpandNamespaceDirectories()) {
          setExpandNamespaceDirectories(other.getExpandNamespaceDirectories());
        }
        if (other.hasClsCompliance()) {
          setClsCompliance(other.getClsCompliance());
        }
        if (other.hasAddSerializable()) {
          setAddSerializable(other.getAddSerializable());
        }
        if (other.hasGeneratePrivateCtor()) {
          setGeneratePrivateCtor(other.getGeneratePrivateCtor());
        }
        if (other.hasFileExtension()) {
          setFileExtension(other.getFileExtension());
        }
        if (other.hasUmbrellaNamespace()) {
          setUmbrellaNamespace(other.getUmbrellaNamespace());
        }
        if (other.hasOutputDirectory()) {
          setOutputDirectory(other.getOutputDirectory());
        }
        if (other.hasIgnoreGoogleProtobuf()) {
          setIgnoreGoogleProtobuf(other.getIgnoreGoogleProtobuf());
        }
        if (other.hasServiceGeneratorType()) {
          setServiceGeneratorType(other.getServiceGeneratorType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              namespace_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              umbrellaClassname_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              publicClasses_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              multipleFiles_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              nestClasses_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              codeContracts_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              expandNamespaceDirectories_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              clsCompliance_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              addSerializable_ = input.readBool();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              generatePrivateCtor_ = input.readBool();
              break;
            }
            case 1770: {
              bitField0_ |= 0x00000400;
              fileExtension_ = input.readBytes();
              break;
            }
            case 1778: {
              bitField0_ |= 0x00000800;
              umbrellaNamespace_ = input.readBytes();
              break;
            }
            case 1786: {
              bitField0_ |= 0x00001000;
              outputDirectory_ = input.readBytes();
              break;
            }
            case 1792: {
              bitField0_ |= 0x00002000;
              ignoreGoogleProtobuf_ = input.readBool();
              break;
            }
            case 1800: {
              int rawValue = input.readEnum();
              google.protobuf.CsharpOptions.CSharpServiceType value = google.protobuf.CsharpOptions.CSharpServiceType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(225, rawValue);
              } else {
                bitField0_ |= 0x00004000;
                serviceGeneratorType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string namespace = 1;
      private java.lang.Object namespace_ = "";
      public boolean hasNamespace() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNamespace() {
        java.lang.Object ref = namespace_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          namespace_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNamespace(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        namespace_ = value;
        onChanged();
        return this;
      }
      public Builder clearNamespace() {
        bitField0_ = (bitField0_ & ~0x00000001);
        namespace_ = getDefaultInstance().getNamespace();
        onChanged();
        return this;
      }
      void setNamespace(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        namespace_ = value;
        onChanged();
      }
      
      // optional string umbrella_classname = 2;
      private java.lang.Object umbrellaClassname_ = "";
      public boolean hasUmbrellaClassname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getUmbrellaClassname() {
        java.lang.Object ref = umbrellaClassname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          umbrellaClassname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUmbrellaClassname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        umbrellaClassname_ = value;
        onChanged();
        return this;
      }
      public Builder clearUmbrellaClassname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        umbrellaClassname_ = getDefaultInstance().getUmbrellaClassname();
        onChanged();
        return this;
      }
      void setUmbrellaClassname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        umbrellaClassname_ = value;
        onChanged();
      }
      
      // optional bool public_classes = 3 [default = true];
      private boolean publicClasses_ = true;
      public boolean hasPublicClasses() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getPublicClasses() {
        return publicClasses_;
      }
      public Builder setPublicClasses(boolean value) {
        bitField0_ |= 0x00000004;
        publicClasses_ = value;
        onChanged();
        return this;
      }
      public Builder clearPublicClasses() {
        bitField0_ = (bitField0_ & ~0x00000004);
        publicClasses_ = true;
        onChanged();
        return this;
      }
      
      // optional bool multiple_files = 4;
      private boolean multipleFiles_ ;
      public boolean hasMultipleFiles() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public boolean getMultipleFiles() {
        return multipleFiles_;
      }
      public Builder setMultipleFiles(boolean value) {
        bitField0_ |= 0x00000008;
        multipleFiles_ = value;
        onChanged();
        return this;
      }
      public Builder clearMultipleFiles() {
        bitField0_ = (bitField0_ & ~0x00000008);
        multipleFiles_ = false;
        onChanged();
        return this;
      }
      
      // optional bool nest_classes = 5;
      private boolean nestClasses_ ;
      public boolean hasNestClasses() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public boolean getNestClasses() {
        return nestClasses_;
      }
      public Builder setNestClasses(boolean value) {
        bitField0_ |= 0x00000010;
        nestClasses_ = value;
        onChanged();
        return this;
      }
      public Builder clearNestClasses() {
        bitField0_ = (bitField0_ & ~0x00000010);
        nestClasses_ = false;
        onChanged();
        return this;
      }
      
      // optional bool code_contracts = 6;
      private boolean codeContracts_ ;
      public boolean hasCodeContracts() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getCodeContracts() {
        return codeContracts_;
      }
      public Builder setCodeContracts(boolean value) {
        bitField0_ |= 0x00000020;
        codeContracts_ = value;
        onChanged();
        return this;
      }
      public Builder clearCodeContracts() {
        bitField0_ = (bitField0_ & ~0x00000020);
        codeContracts_ = false;
        onChanged();
        return this;
      }
      
      // optional bool expand_namespace_directories = 7;
      private boolean expandNamespaceDirectories_ ;
      public boolean hasExpandNamespaceDirectories() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getExpandNamespaceDirectories() {
        return expandNamespaceDirectories_;
      }
      public Builder setExpandNamespaceDirectories(boolean value) {
        bitField0_ |= 0x00000040;
        expandNamespaceDirectories_ = value;
        onChanged();
        return this;
      }
      public Builder clearExpandNamespaceDirectories() {
        bitField0_ = (bitField0_ & ~0x00000040);
        expandNamespaceDirectories_ = false;
        onChanged();
        return this;
      }
      
      // optional bool cls_compliance = 8 [default = true];
      private boolean clsCompliance_ = true;
      public boolean hasClsCompliance() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public boolean getClsCompliance() {
        return clsCompliance_;
      }
      public Builder setClsCompliance(boolean value) {
        bitField0_ |= 0x00000080;
        clsCompliance_ = value;
        onChanged();
        return this;
      }
      public Builder clearClsCompliance() {
        bitField0_ = (bitField0_ & ~0x00000080);
        clsCompliance_ = true;
        onChanged();
        return this;
      }
      
      // optional bool add_serializable = 9 [default = false];
      private boolean addSerializable_ ;
      public boolean hasAddSerializable() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public boolean getAddSerializable() {
        return addSerializable_;
      }
      public Builder setAddSerializable(boolean value) {
        bitField0_ |= 0x00000100;
        addSerializable_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddSerializable() {
        bitField0_ = (bitField0_ & ~0x00000100);
        addSerializable_ = false;
        onChanged();
        return this;
      }
      
      // optional bool generate_private_ctor = 10 [default = true];
      private boolean generatePrivateCtor_ = true;
      public boolean hasGeneratePrivateCtor() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public boolean getGeneratePrivateCtor() {
        return generatePrivateCtor_;
      }
      public Builder setGeneratePrivateCtor(boolean value) {
        bitField0_ |= 0x00000200;
        generatePrivateCtor_ = value;
        onChanged();
        return this;
      }
      public Builder clearGeneratePrivateCtor() {
        bitField0_ = (bitField0_ & ~0x00000200);
        generatePrivateCtor_ = true;
        onChanged();
        return this;
      }
      
      // optional string file_extension = 221 [default = ".cs"];
      private java.lang.Object fileExtension_ = ".cs";
      public boolean hasFileExtension() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getFileExtension() {
        java.lang.Object ref = fileExtension_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fileExtension_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFileExtension(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        fileExtension_ = value;
        onChanged();
        return this;
      }
      public Builder clearFileExtension() {
        bitField0_ = (bitField0_ & ~0x00000400);
        fileExtension_ = getDefaultInstance().getFileExtension();
        onChanged();
        return this;
      }
      void setFileExtension(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        fileExtension_ = value;
        onChanged();
      }
      
      // optional string umbrella_namespace = 222;
      private java.lang.Object umbrellaNamespace_ = "";
      public boolean hasUmbrellaNamespace() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getUmbrellaNamespace() {
        java.lang.Object ref = umbrellaNamespace_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          umbrellaNamespace_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUmbrellaNamespace(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        umbrellaNamespace_ = value;
        onChanged();
        return this;
      }
      public Builder clearUmbrellaNamespace() {
        bitField0_ = (bitField0_ & ~0x00000800);
        umbrellaNamespace_ = getDefaultInstance().getUmbrellaNamespace();
        onChanged();
        return this;
      }
      void setUmbrellaNamespace(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        umbrellaNamespace_ = value;
        onChanged();
      }
      
      // optional string output_directory = 223 [default = "."];
      private java.lang.Object outputDirectory_ = ".";
      public boolean hasOutputDirectory() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getOutputDirectory() {
        java.lang.Object ref = outputDirectory_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          outputDirectory_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOutputDirectory(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        outputDirectory_ = value;
        onChanged();
        return this;
      }
      public Builder clearOutputDirectory() {
        bitField0_ = (bitField0_ & ~0x00001000);
        outputDirectory_ = getDefaultInstance().getOutputDirectory();
        onChanged();
        return this;
      }
      void setOutputDirectory(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        outputDirectory_ = value;
        onChanged();
      }
      
      // optional bool ignore_google_protobuf = 224 [default = false];
      private boolean ignoreGoogleProtobuf_ ;
      public boolean hasIgnoreGoogleProtobuf() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public boolean getIgnoreGoogleProtobuf() {
        return ignoreGoogleProtobuf_;
      }
      public Builder setIgnoreGoogleProtobuf(boolean value) {
        bitField0_ |= 0x00002000;
        ignoreGoogleProtobuf_ = value;
        onChanged();
        return this;
      }
      public Builder clearIgnoreGoogleProtobuf() {
        bitField0_ = (bitField0_ & ~0x00002000);
        ignoreGoogleProtobuf_ = false;
        onChanged();
        return this;
      }
      
      // optional .google.protobuf.CSharpServiceType service_generator_type = 225 [default = NONE];
      private google.protobuf.CsharpOptions.CSharpServiceType serviceGeneratorType_ = google.protobuf.CsharpOptions.CSharpServiceType.NONE;
      public boolean hasServiceGeneratorType() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      public google.protobuf.CsharpOptions.CSharpServiceType getServiceGeneratorType() {
        return serviceGeneratorType_;
      }
      public Builder setServiceGeneratorType(google.protobuf.CsharpOptions.CSharpServiceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00004000;
        serviceGeneratorType_ = value;
        onChanged();
        return this;
      }
      public Builder clearServiceGeneratorType() {
        bitField0_ = (bitField0_ & ~0x00004000);
        serviceGeneratorType_ = google.protobuf.CsharpOptions.CSharpServiceType.NONE;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:google.protobuf.CSharpFileOptions)
    }
    
    static {
      defaultInstance = new CSharpFileOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:google.protobuf.CSharpFileOptions)
  }
  
  public interface CSharpFieldOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string property_name = 1;
    boolean hasPropertyName();
    String getPropertyName();
  }
  public static final class CSharpFieldOptions extends
      com.google.protobuf.GeneratedMessage
      implements CSharpFieldOptionsOrBuilder {
    // Use CSharpFieldOptions.newBuilder() to construct.
    private CSharpFieldOptions(Builder builder) {
      super(builder);
    }
    private CSharpFieldOptions(boolean noInit) {}
    
    private static final CSharpFieldOptions defaultInstance;
    public static CSharpFieldOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSharpFieldOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpFieldOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpFieldOptions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string property_name = 1;
    public static final int PROPERTY_NAME_FIELD_NUMBER = 1;
    private java.lang.Object propertyName_;
    public boolean hasPropertyName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPropertyName() {
      java.lang.Object ref = propertyName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          propertyName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPropertyNameBytes() {
      java.lang.Object ref = propertyName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        propertyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      propertyName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPropertyNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPropertyNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpFieldOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(google.protobuf.CsharpOptions.CSharpFieldOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements google.protobuf.CsharpOptions.CSharpFieldOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpFieldOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpFieldOptions_fieldAccessorTable;
      }
      
      // Construct using google.protobuf.CsharpOptions.CSharpFieldOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        propertyName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.CsharpOptions.CSharpFieldOptions.getDescriptor();
      }
      
      public google.protobuf.CsharpOptions.CSharpFieldOptions getDefaultInstanceForType() {
        return google.protobuf.CsharpOptions.CSharpFieldOptions.getDefaultInstance();
      }
      
      public google.protobuf.CsharpOptions.CSharpFieldOptions build() {
        google.protobuf.CsharpOptions.CSharpFieldOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private google.protobuf.CsharpOptions.CSharpFieldOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        google.protobuf.CsharpOptions.CSharpFieldOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public google.protobuf.CsharpOptions.CSharpFieldOptions buildPartial() {
        google.protobuf.CsharpOptions.CSharpFieldOptions result = new google.protobuf.CsharpOptions.CSharpFieldOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.propertyName_ = propertyName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.CsharpOptions.CSharpFieldOptions) {
          return mergeFrom((google.protobuf.CsharpOptions.CSharpFieldOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(google.protobuf.CsharpOptions.CSharpFieldOptions other) {
        if (other == google.protobuf.CsharpOptions.CSharpFieldOptions.getDefaultInstance()) return this;
        if (other.hasPropertyName()) {
          setPropertyName(other.getPropertyName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              propertyName_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string property_name = 1;
      private java.lang.Object propertyName_ = "";
      public boolean hasPropertyName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPropertyName() {
        java.lang.Object ref = propertyName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          propertyName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPropertyName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        propertyName_ = value;
        onChanged();
        return this;
      }
      public Builder clearPropertyName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        propertyName_ = getDefaultInstance().getPropertyName();
        onChanged();
        return this;
      }
      void setPropertyName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        propertyName_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:google.protobuf.CSharpFieldOptions)
    }
    
    static {
      defaultInstance = new CSharpFieldOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:google.protobuf.CSharpFieldOptions)
  }
  
  public interface CSharpServiceOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string interface_id = 1;
    boolean hasInterfaceId();
    String getInterfaceId();
  }
  public static final class CSharpServiceOptions extends
      com.google.protobuf.GeneratedMessage
      implements CSharpServiceOptionsOrBuilder {
    // Use CSharpServiceOptions.newBuilder() to construct.
    private CSharpServiceOptions(Builder builder) {
      super(builder);
    }
    private CSharpServiceOptions(boolean noInit) {}
    
    private static final CSharpServiceOptions defaultInstance;
    public static CSharpServiceOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSharpServiceOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpServiceOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpServiceOptions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string interface_id = 1;
    public static final int INTERFACE_ID_FIELD_NUMBER = 1;
    private java.lang.Object interfaceId_;
    public boolean hasInterfaceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getInterfaceId() {
      java.lang.Object ref = interfaceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          interfaceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getInterfaceIdBytes() {
      java.lang.Object ref = interfaceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        interfaceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      interfaceId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getInterfaceIdBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getInterfaceIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpServiceOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(google.protobuf.CsharpOptions.CSharpServiceOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements google.protobuf.CsharpOptions.CSharpServiceOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpServiceOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpServiceOptions_fieldAccessorTable;
      }
      
      // Construct using google.protobuf.CsharpOptions.CSharpServiceOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        interfaceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.CsharpOptions.CSharpServiceOptions.getDescriptor();
      }
      
      public google.protobuf.CsharpOptions.CSharpServiceOptions getDefaultInstanceForType() {
        return google.protobuf.CsharpOptions.CSharpServiceOptions.getDefaultInstance();
      }
      
      public google.protobuf.CsharpOptions.CSharpServiceOptions build() {
        google.protobuf.CsharpOptions.CSharpServiceOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private google.protobuf.CsharpOptions.CSharpServiceOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        google.protobuf.CsharpOptions.CSharpServiceOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public google.protobuf.CsharpOptions.CSharpServiceOptions buildPartial() {
        google.protobuf.CsharpOptions.CSharpServiceOptions result = new google.protobuf.CsharpOptions.CSharpServiceOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.interfaceId_ = interfaceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.CsharpOptions.CSharpServiceOptions) {
          return mergeFrom((google.protobuf.CsharpOptions.CSharpServiceOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(google.protobuf.CsharpOptions.CSharpServiceOptions other) {
        if (other == google.protobuf.CsharpOptions.CSharpServiceOptions.getDefaultInstance()) return this;
        if (other.hasInterfaceId()) {
          setInterfaceId(other.getInterfaceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              interfaceId_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string interface_id = 1;
      private java.lang.Object interfaceId_ = "";
      public boolean hasInterfaceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getInterfaceId() {
        java.lang.Object ref = interfaceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          interfaceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setInterfaceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        interfaceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearInterfaceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        interfaceId_ = getDefaultInstance().getInterfaceId();
        onChanged();
        return this;
      }
      void setInterfaceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        interfaceId_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:google.protobuf.CSharpServiceOptions)
    }
    
    static {
      defaultInstance = new CSharpServiceOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:google.protobuf.CSharpServiceOptions)
  }
  
  public interface CSharpMethodOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 dispatch_id = 1;
    boolean hasDispatchId();
    int getDispatchId();
  }
  public static final class CSharpMethodOptions extends
      com.google.protobuf.GeneratedMessage
      implements CSharpMethodOptionsOrBuilder {
    // Use CSharpMethodOptions.newBuilder() to construct.
    private CSharpMethodOptions(Builder builder) {
      super(builder);
    }
    private CSharpMethodOptions(boolean noInit) {}
    
    private static final CSharpMethodOptions defaultInstance;
    public static CSharpMethodOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSharpMethodOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpMethodOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpMethodOptions_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int32 dispatch_id = 1;
    public static final int DISPATCH_ID_FIELD_NUMBER = 1;
    private int dispatchId_;
    public boolean hasDispatchId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getDispatchId() {
      return dispatchId_;
    }
    
    private void initFields() {
      dispatchId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, dispatchId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dispatchId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.CsharpOptions.CSharpMethodOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(google.protobuf.CsharpOptions.CSharpMethodOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements google.protobuf.CsharpOptions.CSharpMethodOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpMethodOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.CsharpOptions.internal_static_google_protobuf_CSharpMethodOptions_fieldAccessorTable;
      }
      
      // Construct using google.protobuf.CsharpOptions.CSharpMethodOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        dispatchId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.CsharpOptions.CSharpMethodOptions.getDescriptor();
      }
      
      public google.protobuf.CsharpOptions.CSharpMethodOptions getDefaultInstanceForType() {
        return google.protobuf.CsharpOptions.CSharpMethodOptions.getDefaultInstance();
      }
      
      public google.protobuf.CsharpOptions.CSharpMethodOptions build() {
        google.protobuf.CsharpOptions.CSharpMethodOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private google.protobuf.CsharpOptions.CSharpMethodOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        google.protobuf.CsharpOptions.CSharpMethodOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public google.protobuf.CsharpOptions.CSharpMethodOptions buildPartial() {
        google.protobuf.CsharpOptions.CSharpMethodOptions result = new google.protobuf.CsharpOptions.CSharpMethodOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dispatchId_ = dispatchId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.CsharpOptions.CSharpMethodOptions) {
          return mergeFrom((google.protobuf.CsharpOptions.CSharpMethodOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(google.protobuf.CsharpOptions.CSharpMethodOptions other) {
        if (other == google.protobuf.CsharpOptions.CSharpMethodOptions.getDefaultInstance()) return this;
        if (other.hasDispatchId()) {
          setDispatchId(other.getDispatchId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              dispatchId_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 dispatch_id = 1;
      private int dispatchId_ ;
      public boolean hasDispatchId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDispatchId() {
        return dispatchId_;
      }
      public Builder setDispatchId(int value) {
        bitField0_ |= 0x00000001;
        dispatchId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDispatchId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dispatchId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:google.protobuf.CSharpMethodOptions)
    }
    
    static {
      defaultInstance = new CSharpMethodOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:google.protobuf.CSharpMethodOptions)
  }
  
  public static final int CSHARP_FILE_OPTIONS_FIELD_NUMBER = 1000;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.FileOptions,
      google.protobuf.CsharpOptions.CSharpFileOptions> csharpFileOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        google.protobuf.CsharpOptions.CSharpFileOptions.class,
        google.protobuf.CsharpOptions.CSharpFileOptions.getDefaultInstance());
  public static final int CSHARP_FIELD_OPTIONS_FIELD_NUMBER = 1000;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.FieldOptions,
      google.protobuf.CsharpOptions.CSharpFieldOptions> csharpFieldOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        google.protobuf.CsharpOptions.CSharpFieldOptions.class,
        google.protobuf.CsharpOptions.CSharpFieldOptions.getDefaultInstance());
  public static final int CSHARP_SERVICE_OPTIONS_FIELD_NUMBER = 1000;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.ServiceOptions,
      google.protobuf.CsharpOptions.CSharpServiceOptions> csharpServiceOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        google.protobuf.CsharpOptions.CSharpServiceOptions.class,
        google.protobuf.CsharpOptions.CSharpServiceOptions.getDefaultInstance());
  public static final int CSHARP_METHOD_OPTIONS_FIELD_NUMBER = 1000;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      google.protobuf.DescriptorProtos.MethodOptions,
      google.protobuf.CsharpOptions.CSharpMethodOptions> csharpMethodOptions = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        google.protobuf.CsharpOptions.CSharpMethodOptions.class,
        google.protobuf.CsharpOptions.CSharpMethodOptions.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_CSharpFileOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_CSharpFileOptions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_CSharpFieldOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_CSharpFieldOptions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_CSharpServiceOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_CSharpServiceOptions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_CSharpMethodOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_CSharpMethodOptions_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$protobuf/google/csharp_options.proto\022\017" +
      "google.protobuf\032 protobuf/google/descrip" +
      "tor.proto\"\374\003\n\021CSharpFileOptions\022\021\n\tnames" +
      "pace\030\001 \001(\t\022\032\n\022umbrella_classname\030\002 \001(\t\022\034" +
      "\n\016public_classes\030\003 \001(\010:\004true\022\026\n\016multiple" +
      "_files\030\004 \001(\010\022\024\n\014nest_classes\030\005 \001(\010\022\026\n\016co" +
      "de_contracts\030\006 \001(\010\022$\n\034expand_namespace_d" +
      "irectories\030\007 \001(\010\022\034\n\016cls_compliance\030\010 \001(\010" +
      ":\004true\022\037\n\020add_serializable\030\t \001(\010:\005false\022" +
      "#\n\025generate_private_ctor\030\n \001(\010:\004true\022\034\n\016",
      "file_extension\030\335\001 \001(\t:\003.cs\022\033\n\022umbrella_n" +
      "amespace\030\336\001 \001(\t\022\034\n\020output_directory\030\337\001 \001" +
      "(\t:\001.\022&\n\026ignore_google_protobuf\030\340\001 \001(\010:\005" +
      "false\022I\n\026service_generator_type\030\341\001 \001(\0162\"" +
      ".google.protobuf.CSharpServiceType:\004NONE" +
      "\"+\n\022CSharpFieldOptions\022\025\n\rproperty_name\030" +
      "\001 \001(\t\",\n\024CSharpServiceOptions\022\024\n\014interfa" +
      "ce_id\030\001 \001(\t\"*\n\023CSharpMethodOptions\022\023\n\013di" +
      "spatch_id\030\001 \001(\005*K\n\021CSharpServiceType\022\010\n\004" +
      "NONE\020\000\022\013\n\007GENERIC\020\001\022\r\n\tINTERFACE\020\002\022\020\n\014IR",
      "PCDISPATCH\020\003:^\n\023csharp_file_options\022\034.go" +
      "ogle.protobuf.FileOptions\030\350\007 \001(\0132\".googl" +
      "e.protobuf.CSharpFileOptions:a\n\024csharp_f" +
      "ield_options\022\035.google.protobuf.FieldOpti" +
      "ons\030\350\007 \001(\0132#.google.protobuf.CSharpField" +
      "Options:g\n\026csharp_service_options\022\037.goog" +
      "le.protobuf.ServiceOptions\030\350\007 \001(\0132%.goog" +
      "le.protobuf.CSharpServiceOptions:d\n\025csha" +
      "rp_method_options\022\036.google.protobuf.Meth" +
      "odOptions\030\350\007 \001(\0132$.google.protobuf.CShar",
      "pMethodOptions"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_google_protobuf_CSharpFileOptions_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_google_protobuf_CSharpFileOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_google_protobuf_CSharpFileOptions_descriptor,
              new java.lang.String[] { "Namespace", "UmbrellaClassname", "PublicClasses", "MultipleFiles", "NestClasses", "CodeContracts", "ExpandNamespaceDirectories", "ClsCompliance", "AddSerializable", "GeneratePrivateCtor", "FileExtension", "UmbrellaNamespace", "OutputDirectory", "IgnoreGoogleProtobuf", "ServiceGeneratorType", },
              google.protobuf.CsharpOptions.CSharpFileOptions.class,
              google.protobuf.CsharpOptions.CSharpFileOptions.Builder.class);
          internal_static_google_protobuf_CSharpFieldOptions_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_google_protobuf_CSharpFieldOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_google_protobuf_CSharpFieldOptions_descriptor,
              new java.lang.String[] { "PropertyName", },
              google.protobuf.CsharpOptions.CSharpFieldOptions.class,
              google.protobuf.CsharpOptions.CSharpFieldOptions.Builder.class);
          internal_static_google_protobuf_CSharpServiceOptions_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_google_protobuf_CSharpServiceOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_google_protobuf_CSharpServiceOptions_descriptor,
              new java.lang.String[] { "InterfaceId", },
              google.protobuf.CsharpOptions.CSharpServiceOptions.class,
              google.protobuf.CsharpOptions.CSharpServiceOptions.Builder.class);
          internal_static_google_protobuf_CSharpMethodOptions_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_google_protobuf_CSharpMethodOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_google_protobuf_CSharpMethodOptions_descriptor,
              new java.lang.String[] { "DispatchId", },
              google.protobuf.CsharpOptions.CSharpMethodOptions.class,
              google.protobuf.CsharpOptions.CSharpMethodOptions.Builder.class);
          csharpFileOptions.internalInit(descriptor.getExtensions().get(0));
          csharpFieldOptions.internalInit(descriptor.getExtensions().get(1));
          csharpServiceOptions.internalInit(descriptor.getExtensions().get(2));
          csharpMethodOptions.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
